name: Build
on:
  release:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - name: Install Android API Level 32
        run: sdkmanager "platform-tools" "platforms;android-32"

      - name: Install `libtinfo5`
        run: |
          sudo apt-get update
          wget --content-disposition http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt-get install -y ./libtinfo5_6.3-2ubuntu0.1_amd64.deb

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build ZetaSQL
        shell: bash
        run: |
          bazel clean --expunge
          bazel --host_jvm_args=-Xmx2g build ... --verbose_failures --discard_analysis_cache --notrack_incremental_state --nokeep_state_after_build --local_resources=memory=HOST_RAM*.90 --noremote_accept_cached --remote_upload_local_results=false --disk_cache='' --repository_cache='' --cache_computed_file_digests=0 
