name: Build
on:
  release:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - run: sdkmanager "platform-tools" "platforms;android-33"

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build ZetaSQL
        shell: bash
        run: |
          bazel build ...
